name: dockerimage-ngx

on:
  push:
    tags:
      - ngx-image*
    branches-ignore:
      - 'translations**'

jobs:

  # build and push image to docker hub.
  build-docker-image:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/ngx-image')
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          if [[ $GITHUB_REF == refs/tags/ngx-* ]]; then
            TAGS=${IMAGE_NAME}:${GITHUB_REF#refs/tags/ngx-},${IMAGE_NAME}:latest
            INSPECT_TAG=${IMAGE_NAME}:latest
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            TAGS=${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
            INSPECT_TAG=${TAGS}
          else
            exit 1
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=inspect_tag::${INSPECT_TAG}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ steps.prepare.outputs.inspect_tag }}